bases/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from bases.views import Home, HomeSinPrivilegios, getEstadisticas

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='bases/login.html'), name='logout'),
    path('sin_privilegios/', HomeSinPrivilegios.as_view(), name="sin_privilegios"),
    path('bases/obtener-estadisticas/', getEstadisticas, name="obtener-estadisticas")
]

catastro/urls.py
from django.urls import path
from .views import ContribuyenteView, ContribuyenteNew, ContribuyenteEdit, ContribuyenteDelete

urlpatterns = [
    # crud de contribuyentes
    path('contribuyentes/', ContribuyenteView.as_view(), name='contribuyentes_list'),
    path('contribuyentes/new', ContribuyenteNew.as_view(), name='contribuyentes_new'),
    path('contribuyentes/edit/<int:pk>', ContribuyenteEdit.as_view(), name='contribuyentes_edit'),
    path('contribuyentes/delete/<int:pk>', ContribuyenteDelete.as_view(), name='contribuyentes_delete'),
]

gestion_apoyos/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('apoyos/', include(('apoyos.urls', 'apoyos'), namespace='apoyos')),
    path('catastro/', include(('catastro.urls', 'catastro'), namespace='catastro')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catastro/models.py
from django.db import models

# Create your models here.
class Contribuyente(models.Model):
    """ modelo de contribuyente """
    
    numero_de_cuenta_predial = models.IntegerField(
        unique=True,
        null=True,
        blank=True
    )
    
    nombre = models.CharField(max_length=100)
    ap_paterno = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

    ap_materno = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )
    
    M = 'MASCULINO'
    F = 'FEMENINO'
    GENERO = [
        (M, 'MASCULINO'),
        (F, 'FEMENINO')
    ]
    genero = models.CharField(
        max_length=15,
        choices=GENERO,
        default=M        
    )
    
    domicilio = models.CharField(
        max_length=250,
        blank=True,
        null=True
    )
    
    localidad = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

    telefono = models.BigIntegerField(
        blank=True,
        null=True
    )
        
    expediente = models.FileField(upload_to="expedientes/", null=True, blank=True)
    
    notas_adicionales = models.CharField(
        max_length=500,
        null=True,
        blank=True
    )
    
    def __str__(self):
        """ Descripción del modelo contribuyente """
        return '{} {} {}'.format(self.nombre, self.ap_paterno, self.ap_materno)
    
    def save(self):
        """ el nombre del contribuyente lo guardamos en mayúsculas"""
        self.nombre = self.nombre.upper()
        if self.ap_paterno: # si la cadena esta llena
            self.ap_paterno = self.ap_paterno.upper()
            
        if self.ap_materno: # si la cadena esta llena
            self.ap_materno = self.ap_materno.upper()
            
        super(Contribuyente, self).save()

    class Meta:
        """ nombre en plural(Muchos) del modelo"""
        verbose_name_plural = "Contribuyentes"

catastro/forms.py
from django import forms
from .models import Contribuyente
from .validators import MaxSizeFileValidator
from django.forms import ValidationError

class ContribuyenteForm(forms.ModelForm):
    """ form de contribuyente"""
    
    # validaciones en el lado del servidor
    numero_de_cuenta_predial = forms.IntegerField(min_value=1, required=True)
    nombre = forms.CharField(min_length=1, max_length=100, required=True)
    ap_paterno = forms.CharField(required=True)
    expediente = forms.FileField(required=False)
    localidad = forms.CharField(required=True)
    telefono = forms.IntegerField(required=True)
    
    # validamos que no haya registros duplicados con el mismo numero de predial
    # def clean_numero_de_cuenta_predial(self):
        # extraemos el valor que ingreso el usuario en el campo
        # numero_de_cuenta_predial = self.cleaned_data["numero_de_cuenta_predial"] 
        # existe = Contribuyente.objects.filter(numero_de_cuenta_predial=numero_de_cuenta_predial).exists()
        
        # if existe:
        #   raise ValidationError("Ya existe un contribuyentre con este numero de predial..")      
      
        # return numero_de_cuenta_predial

    class Meta:
        model = Contribuyente
        # campos que muestra el form
        fields = ("numero_de_cuenta_predial", "nombre", "ap_paterno", "ap_materno", "genero", "domicilio", "localidad", "telefono", "expediente", "notas_adicionales")
        # etiquetas
        labels = {
            "numero_de_cuenta_predial": "Número de cuenta predial", 
            "nombre": "Nombre",
            "ap_paterno": "Apellido Paterno",
            "ap_materno": "Apellido Materno",
            "genero": "Género",
            "localidad": "Localidad",
            "expediente": "Expediente",
            "notas_adicionales": "Notas Adicionales" 
        }
                    
    def __init__(self, *args, **kwargs):
        """ método que itera los campos del form y agrega la clase form-control de bootstrap a los input"""
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
            
    def clean(self):
        try:
            sc = Contribuyente.objects.get(
                numero_de_cuenta_predial = self.cleaned_data['numero_de_cuenta_predial']
            )
            
            if not self.instance.pk:
                raise ValidationError("Ya existe un contribuyente con este numero de predial..")
            elif self.instance.pk != sc.pk:
                raise forms.ValidationError("Cambio no permitido, coincide con otro registro")
            
        except Contribuyente.DoesNotExist:
            pass            
        return self.cleaned_data

catastro/views.py
from django.shortcuts import render, redirect
from .models import Contribuyente
from bases.views import Sin_Privilegios
from django.views import generic
from .forms import ContribuyenteForm
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

# Create your views here.
class ContribuyenteView(Sin_Privilegios, generic.ListView):
    """ vista basada en clase para listar localidades"""
    permission_required = "catastro.view_contribuyente"
    model = Contribuyente
    template_name = "catastro/contribuyentes_list.html"
    context_object_name = "obj" 
    
class ContribuyenteNew(SuccessMessageMixin, Sin_Privilegios, generic.CreateView):
    """ vista basada en clase para agregar contribuyentes"""
    permission_required = "catastro.add_contribuyente"
    model = Contribuyente
    template_name = "catastro/contribuyentes_form.html"
    context_object_name = "obj"
    form_class = ContribuyenteForm
    success_message = "Contribuyente agregado satisfactoriamente.."
    success_url = reverse_lazy("catastro:contribuyentes_list")
        
class ContribuyenteEdit(SuccessMessageMixin, Sin_Privilegios, generic.UpdateView):
    """ vista basada en clase para actualizar contribuyentes"""
    permission_required = "catastro.change_contribuyente"
    model = Contribuyente
    template_name = "catastro/contribuyentes_form.html"
    context_object_name = "obj"
    form_class = ContribuyenteForm
    success_message = "Contribuyente actualizado satisfactoriamente.."
    success_url = reverse_lazy("catastro:contribuyentes_list")
    
class ContribuyenteDelete(SuccessMessageMixin, Sin_Privilegios, generic.DeleteView):
    """ vista basada en clase para eliminar contribuyentes"""
    permission_required = "catastro.delete_contribuyente"
    model = Contribuyente
    template_name = "catastro/contribuyentes_del.html"
    context_object_name = "obj"
    success_message = "Contribuyente eliminado satisfactoriamente.."
    success_url = reverse_lazy("catastro:contribuyentes_list")
    

catastro/templates/catastro/contribuyentes_del.html
{% extends 'base/base.html' %}

{% block page_content %}
   <form method="POST" class="form-inline">
       {% csrf_token %}
        <div class="col-xl-3 col-md-6 mb-4">   
            <div class="card border-left-danger shadow h-100 py-2">                            
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1"> ¿Eliminar registro de contribuyente: {{ obj.nombre }} {{ obj.ap_paterno }}?</div>
                            <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i>Si, Eliminar</button>
                            <a href="{% url 'catastro:contribuyentes_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>      
                        
                        <div class="col-auto">
                            <i class="far fa-question-circle fa-2x text-gray-300"></i>                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
   </form>  
{% endblock page_content %}    
{% block js_page %} {% endblock js_page %}

catastro/templates/catastro/contribuyentes_form.html
{% extends 'base/base.html' %}

{% load static %}

{% block page_content %}
   <form method="POST" class="form-inline" enctype="multipart/form-data">
       {% csrf_token %}
        <div class="col-xl-12 col-md-12 mb-12">
            
            {% if obj %}      
                <div class="card border-left-warning shadow h-100 py-2">
            {% else %}
                <div class="card border-left-success shadow h-100 py-2">
            {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if obj %} Editar {% else %} Nuevo {% endif %} Contribuyente
                            </div>                        
                            <div class="dropdown-divider"></div>  
                            
                            <div class="col mb-3">
                                <div class="card" style="width: 64rem;">
                                    <img src="{% static 'base/img/contribuyentes_edit.svg' %}" class="card-img-top" alt="..." height="200px" width="200px">
                                    <div class="card-body">
                                      <h5 class="card-title text-md-center">Contribuyentes Registrados - Presidencia Municipal</h5>                                      
                                    </div>
                                </div>
                            </div>
                           
                            <!-- {{ form.errors }} -->

                            <div class="row mb-3">
                                <div class="col-md-2"></div>
                                <div class="col-md-8 text-uppercase font-weight-bold">
                                    {{ form.numero_de_cuenta_predial.label }}:
                                    <div class="input-group">
                                        {{ form.numero_de_cuenta_predial }}
                                    </div>
                                </div>
                            </div>
                            
                            <!-- fila 1 -->
                            <div class="row mb-3">
                                <div class="col-md-4 text-uppercase font-weight-bold">
                                    {{ form.nombre.label }}:
                                    <div class="input-group">                                        
                                        {{ form.nombre }}
                                    </div>
                                </div>
                                <div class="col-md-4 text-uppercase font-weight-bold">
                                    {{ form.ap_paterno.label }}:
                                    <div class="input-group">
                                        {{ form.ap_paterno }}
                                    </div>
                                </div>
                                <div class="col-md-4 text-uppercase font-weight-light">
                                    {{ form.ap_materno.label }}:
                                    <div class="input-group">
                                        {{ form.ap_materno }}
                                    </div>
                                </div>
                            </div>

                            <!-- fila 2 -->
                            <div class="row mb-3">
                                <div class="col-md-4 text-uppercase font-weight-light">
                                    {{ form.genero.label }}:
                                    <div class="input-group">
                                        {{ form.genero }}
                                    </div>
                                </div>

                                <div class="col-md-4 text-uppercase font-weight-light">
                                    {{ form.domicilio.label }}:
                                    <div class="input-group">
                                        {{ form.domicilio }}
                                    </div>
                                </div>
                                
                                <div class="col-md-4 text-uppercase font-weight-bold">
                                    {{ form.localidad.label }}:
                                    <div class="input-group">
                                        {{ form.localidad }}
                                    </div>
                                </div>
                                
                            </div>

                            <!-- fila 3 -->
                            <div class="row mb-3">
                                <div class="col-md-4 text-uppercase font-weight-bold">
                                    {{ form.telefono.label }}:
                                    <div class="input-group">
                                        {{ form.telefono }}
                                    </div>
                                </div>

                                <div class="col-md-4 text-uppercase font-weight-light">
                                    {{ form.expediente.label }}:
                                    <div class="input-group">
                                        {{ form.expediente }}
                                    </div>
                                </div>

                                <div class="col-md-4 text-uppercase font-weight-light">
                                    {{ form.notas_adicionales.label }}:
                                    <div class="input-group">
                                        {{ form.notas_adicionales }}
                                    </div>
                                </div>                                
                            </div>                           
                            
                            <!-- {{ form.as_p }} -->
                            <div class="dropdown-divider"></div>
                            <div class="row mt-3">
                                 <div class="col">
                                    <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                                    <a href="{% url 'catastro:contribuyentes_list' %}" class="btn btn-success"><span class="fa fa-undo">Cancelar</span></a>
                                </div>
                            </div>                                
                            
                        </div>                        
                    </div>
                </div>
            </div>
        </div>
   </form>  
{% endblock page_content %}    
{% block js_page %}
    <script>
        {% if form.errors %}
            //si el formulario tiene errores
            {% for field in form %}
                {% if field.errors %}
                    {% for error in field.errors %}
                        mensaje('{{ error|escape }}', 'red')
                    {% endfor %}
                {% endif %}
            {% endfor %}
        {% endif %}


        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                mensaje('{{ error|escape }}', 'red')
            {% endfor %}
        {% endif %}
    </script>
{% endblock js_page %}


    

catastro/templates/catastro/contribuyentes_list.html
{% extends 'base/base.html' %}

{% block page_content %}
 <!-- Dropdown Card Example -->
 <div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de Contribuyentes - Pinos, Zacatecas</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                    <a class="dropdown-item" href="{% url 'catastro:contribuyentes_new' %}"> <i class="fa fa-calendar-plus"></i>Nuevo</a>
                    <!-- <a class="dropdown-item" href="#">Another action</a> -->
                <div class="dropdown-divider"></div>
                <!-- <a class="dropdown-item" href="#">Something else here</a> -->
            </div>
        </div>
    </div>

    <div class="card-body">
        {% if not obj %}
            <div class="alert alert-info">No Hay Contribuyentes</div>           
        {% else %}

        <table class="table table-bordered table-striped">
            <thead>
                <!-- <td>ID</td> -->
                <th>NÚMERO DE PREDIAL</th>
                <th>NOMBRE</th>
                <th>AP PATERNO</th>
                <th>AP MATERNO</th>
                <th>GÉNERO</th>
                <!-- <th>LOCALIDAD</th> -->
                <!-- <th>EXPEDIENTE</th> -->
                <!-- <th>NOTAS ADICIONALES</th> -->
                <th>ACCIONES</th>
            </thead>
    
            <tbody>
                
                {% for item in obj %}
                    <tr>
                        <!-- <td>{{ item.id }}</td> -->                       
                        {% if item.numero_de_cuenta_predial %}
                            <td>{{ item.numero_de_cuenta_predial }}</td>
                        {% else %}
                            <td></td>
                        {% endif %}                           

                        {% if item.nombre %}
                            <td>{{ item.nombre }}</td>                    
                        {% else %}
                            <td></td>
                        {% endif %}
                                                
                        {% if item.ap_paterno %}
                            <td>{{ item.ap_paterno }}</td>
                        {% else %}
                            <td></td>
                        {% endif %}
                                                                                       
                        {% if item.ap_materno %}
                            <td>{{ item.ap_materno }}</td>                    
                        {% else %}
                            <td></td>
                        {% endif %}
    
                        <!-- {% if item.genero %}
                            <td>{{ item.genero }}</td>                    
                        {% else %}
                            <td></td>
                        {% endif %} -->
    
                        {% if item.localidad %}
                            <td>{{ item.localidad }}</td>                    
                        {% else %} 
                            <td></td>
                        {% endif %}
                        
                        <!-- {% if item.expediente %}
                            <td>{{ item.expediente }}</td>                            
                        {% else %} 
                            <td></td>
                        {% endif %} -->
                            
                            
                        <!-- {% if item.notas_adicionales %}
                            <td>{{ item.notas_adicionales }}</td>
                        {% else %} 
                            <td></td>
                        {% endif %} -->
                            
                        <td>
                            <a href="{% url 'catastro:contribuyentes_edit' item.id %}" class="btn btn-warning btn-circle"><i class="far fa-edit"></i></a>                           
                            <a href="{% url 'catastro:contribuyentes_delete' item.id %}" class="btn btn-danger btn-circle"><i class="fas fa-trash-alt"></i> </a>                            
                        </td>
                    </tr>                                     
                {% endfor %}
                    
            </tbody>
        </table>
        {% endif %}
        
    </div>
</div>
{% endblock page_content %}

{% block js_page %}
    <script>
        // llamamos al plugin datatable de jQuery
        $(document).ready( function () {
            $('.table').DataTable({
                "pageLength": 8,
                "language": {
                    "processing": "Procesando...",
                    "lengthMenu": "Mostrar _MENU_ registros",
                    "zeroRecords": "No se encontraron resultados",
                    "emptyTable": "Ningún dato disponible en esta tabla",
                    "infoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "infoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "search": "Buscar:",
                    "infoThousands": ",",
                    "loadingRecords": "Cargando...",
                    "paginate": {
                        "first": "Primero",
                        "last": "Último",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    },
                    "aria": {
                        "sortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sortDescending": ": Activar para ordenar la columna de manera descendente"
                    },                    
                }
            });
        });
         
    </script>
{% endblock js_page %}